### ISSUE TITLE
Feilmeldinger ved kjøring av pakke

### ISSUE THREAD

**Issue by vidstra** [statisticsnorway/ssb-altinn-python#252]
Jeg får en del feilmeldinger som ikke har dukket opp tidligere når jeg forsøker å bruke pakken 'ssb-altinn-python'. Jeg mistenker at problemet ligger i sjekken is_dapla(). Har funnet disse linjene i Python-koden:

jupyter_image_spec: Optional[str] = os.environ.get("JUPYTER_IMAGE_SPEC")
return bool(jupyter_image_spec and "dapla-jupyterlab" in jupyter_image_spec)

Men når jeg tar en sjekk på os.environ.get("JUPYTER_IMAGE_SPEC") i jupyterlab så får jeg dette:

[europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-stat-docker/jupyter/jupyterlab-dapla:v1.6.11](http://europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-stat-docker/jupyter/jupyterlab-dapla:v1.6.11)

Ser altså ut til at sjekken is_dapla() ikke finner strengen ‘dapla-jupyterlab’, og den nå heter ‘jupyterlab-dapla’ i os.environ.get("JUPYTER_IMAGE_SPEC")

**Comment by skars82** [comment]
Fikset i versjon 0.3.4. Ligger ute på Pypi. Du kan installere med `poetry add ssb-altinn-python@0.3.4`
